version: "3"
services:
  # naming based on use case, not of technology
  #App - custom image, we need to define it from where to build it
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    image: shippingdocker/app:latest 
    networks:
      - appnet
    volumes: 
      - ./application:/var/www/html
    working_dir: /var/www/html
  cache: 
    image: redis:alpine
    networks:
      - appnet
    volumes:
      - cachedata:/data
  db:
    image: mysql:5.7
    networks:
      - appnet
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    image: shippingdocker/node:latest
    networks:
     - appnet
    volumes:
      - ./application:/opt
    working_dir: /opt

networks:
  appnet:
    driver: bridge
volumes:
  dbdata:
    driver: local
  cachedata:
    driver: local