version: "3"
services:
  # naming based on use case, not of technology
  #App - custom image, we need to define it from where to build it
  app:
    build:
      context: ./docker/app
      dockerfile: ./docker/app/Dockerfile
    image: shippingdocker/app:latest 
    networks:
      - appnet
    volumes: 
      - ./application:/var/www/html
    ports: 
      - ${APP_PORT}:80
    working_dir: /var/www/html
  cache: 
    image: redis:alpine
    networks:
      - appnet
    volumes:
      - cachedata:/data
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    networks:
      - appnet
    volumes:
      - dbdata:/var/lib/mysql
    ports: 
      - ${DB_PORT}:3306
networks:
  appnet:
    driver: bridge
volumes:
  dbdata:
    driver: local
  cachedata:
    driver: local
